=== ProjectCRN/ProductsStore/src/main/resources/xml-parser/catalogSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalog">
        <xs:complexType >
            <xs:choice maxOccurs="unbounded">
                <xs:element name="tablet" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name = "name" type="xs:string">
                            </xs:element>
                            <xs:element name = "attributes">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "price" type="xs:decimal" nillable="false"></xs:element>
                                        <xs:element name = "summary" type="xs:string"></xs:element>
                                        <xs:element name = "operatingsystem" type="xs:string" nillable="false"></xs:element>
                                        <xs:element name = "processorspeed" type="xs:decimal"></xs:element>
                                        <xs:element name = "capacity" type="xs:integer"></xs:element>
                                        <xs:element name = "display" type="xs:decimal"></xs:element>
                                        <xs:element name = "height" type="xs:decimal"></xs:element>
                                        <xs:element name = "width" type="xs:decimal"></xs:element>
                                        <xs:element name = "depth" type="xs:decimal"></xs:element>
                                        <xs:element name = "weight" type="xs:decimal"></xs:element>
                                        <xs:element name = "camera" type="xs:decimal"></xs:element>
                                        <xs:element name = "battery" type="xs:decimal"></xs:element>
                                        <xs:element name = "simcard" type="xs:string"></xs:element>
                                        <xs:element name = "fabricator" type="xs:string"></xs:element>
                                        <xs:element name = "imageurl" type="xs:anyURI"></xs:element>
                                     </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="telephone" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name = "name" type="xs:string">
                            </xs:element>
                            <xs:element name = "attributes">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "price" type="xs:decimal" nillable="false"></xs:element>
                                        <xs:element name = "summary" type="xs:string"></xs:element>
                                        <xs:element name = "operatingsystem" type="xs:string" nillable="false"></xs:element>
                                        <xs:element name = "processorspeed" type="xs:decimal"></xs:element>
                                        <xs:element name = "capacity" type="xs:integer"></xs:element>
                                        <xs:element name = "display" type="xs:decimal"></xs:element>
                                        <xs:element name = "height" type="xs:decimal"></xs:element>
                                        <xs:element name = "width" type="xs:decimal"></xs:element>
                                        <xs:element name = "depth" type="xs:decimal"></xs:element>
                                        <xs:element name = "weight" type="xs:decimal"></xs:element>
                                        <xs:element name = "camera" type="xs:decimal"></xs:element>
                                        <xs:element name = "battery" type="xs:decimal"></xs:element>
                                        <xs:element name = "simcard" type="xs:string"></xs:element>
                                        <xs:element name = "fabricator" type="xs:string"></xs:element>
                                        <xs:element name = "imageurl" type="xs:anyURI"></xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType >
    </xs:element>
</xs:schema>

=== ProjectCRN/ProductsStore/src/main/webapp/resources/xml-parser/generatedCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogSchema.xsd">
  <telephone>
    <name>iPhone5S</name>
    <attributes>
      <price>258.0</price>
      <summary>Apple iPhone 5s smartphone was launched in September 2013</summary>
      <operatingsystem>iOS 7</operatingsystem>
      <processorspeed>1.3</processorspeed>
      <capacity>16</capacity>
      <display>4.0</display>
      <height>123.8</height>
      <width>58.6</width>
      <depth>7.6</depth>
      <weight>112</weight>
      <camera>8</camera>
      <battery>10</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Apple</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </telephone>
  <telephone>
    <name>iPhone 36S</name>
    <attributes>
      <price>549.0</price>
      <summary>IPhone 36s embody Apples continuing environmental progress</summary>
      <operatingsystem>iOS 10</operatingsystem>
      <processorspeed>1.8</processorspeed>
      <capacity>32</capacity>
      <display>4.7</display>
      <height>138.3</height>
      <width>67.1</width>
      <depth>7.1</depth>
      <weight>143</weight>
      <camera>12</camera>
      <battery>14</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Apple</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </telephone>
  <telephone>
    <name>iPhone6S</name>
    <attributes>
      <price>549.0</price>
      <summary>IPhone 6s embody Apples continuing environmental progress</summary>
      <operatingsystem>iOS 10</operatingsystem>
      <processorspeed>1.8</processorspeed>
      <capacity>32</capacity>
      <display>4.7</display>
      <height>138.3</height>
      <width>67.1</width>
      <depth>7.1</depth>
      <weight>143</weight>
      <camera>12</camera>
      <battery>14</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Apple</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </telephone>
  <telephone>
    <name>Raskladushka</name>
    <attributes>
      <price>228</price>
      <summary>blabalbal</summary>
      <operatingsystem>iOS 700</operatingsystem>
      <processorspeed>1.23</processorspeed>
      <capacity>126</capacity>
      <display>42.0</display>
      <height>1232.8</height>
      <width>58.6</width>
      <depth>7.6</depth>
      <weight>112</weight>
      <camera>8</camera>
      <battery>10</battery>
      <simcard>SIMSALABIM</simcard>
      <fabricator>Appelsin</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </telephone>
  <telephone>
    <name>Galaxy S7 Edge</name>
    <attributes>
      <price>769.99</price>
      <summary>Samsung has created a beautiful phone with water resistance and fast loading</summary>
      <operatingsystem>Android 6.0</operatingsystem>
      <processorspeed>2.15</processorspeed>
      <capacity>32</capacity>
      <display>5.5</display>
      <height>150.9</height>
      <width>72.6</width>
      <depth>7.7</depth>
      <weight>157</weight>
      <camera>12</camera>
      <battery>13</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Samsung</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </telephone>
  <telephone>
    <name>Galaxy S72Edge</name>
    <attributes>
      <price>769.99</price>
      <summary>Samsung has created a beautiful phone with water resistance and fast loading</summary>
      <operatingsystem>Android 6.0</operatingsystem>
      <processorspeed>2.15</processorspeed>
      <capacity>32</capacity>
      <display>5.5</display>
      <height>150.9</height>
      <width>72.6</width>
      <depth>7.7</depth>
      <weight>157</weight>
      <camera>12</camera>
      <battery>13</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Samsung</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </telephone>
  <tablet>
    <name>iPad mini 4</name>
    <attributes>
      <price>399</price>
      <operatingsystem>iOS</operatingsystem>
      <processorspeed>1.5</processorspeed>
      <capacity>32</capacity>
      <display>7.9</display>
      <height>203.2</height>
      <width>134.8</width>
      <depth>6.1</depth>
      <weight>298.8</weight>
      <camera>8</camera>
      <battery>10</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Apple</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </tablet>
  <tablet>
    <name>iPadmini413</name>
    <attributes>
      <price>399</price>
      <summary>some summary</summary>
      <operatingsystem>iOS</operatingsystem>
      <processorspeed>1.5</processorspeed>
      <capacity>32</capacity>
      <display>7.9</display>
      <height>203.2</height>
      <width>134.8</width>
      <depth>6.1</depth>
      <weight>298.8</weight>
      <camera>8</camera>
      <battery>10</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Apple</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </tablet>
  <tablet>
    <name>iPad Air 2</name>
    <attributes>
      <price>399</price>
      <summary>iPad Air 2</summary>
      <operatingsystem>iOS</operatingsystem>
      <processorspeed>1.5</processorspeed>
      <capacity>32</capacity>
      <display>9.7</display>
      <height>240</height>
      <width>169.5</width>
      <depth>6.1</depth>
      <weight>437</weight>
      <camera>8</camera>
      <battery>10</battery>
      <simcard>Nano-SIM</simcard>
      <fabricator>Apple</fabricator>
      <imageurl>/resources/img/img_phone.jpg</imageurl>
    </attributes>
  </tablet>
</catalog>
